name: Java CI with Gradle

on:
  push:
    branches: [ "study" ]

env:
  AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }} # S3 버킷 이름
  AWS_CODE_DEPLOY_NAME: ${{ secrets.AWS_CODE_DEPLOY_NAME }} # CodeDeploy 애플리케이션 이름
  AWS_CODE_DEPLOY_GROUP: ${{ secrets.AWS_CODE_DEPLOY_GROUP }} # CodeDeploy 배포 그룹 이름


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v3

      - name: set JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Run chmod to make gradlew executable
        run: chmod +x gradlew

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Docker build
        run: docker build -t ${{ env.AWS_ECR_URI }}:latest ./

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Publish Image to ECR
        run: |
          docker push ${{ env.AWS_ECR_URI }}:latest

      # Docker 이미지 이름을 image.txt 파일에 쓰기
      - name: Write Docker image name to file
        run: echo "${{ env.AWS_ECR_URI }}:latest" > image.txt

      # Docker compose에 새 이미지명 쓰기
      - name: Docker compose sed
        run: sed -i 's/_IMAGE_NAME_/${{ env.AWS_ECR_URI }}:latest/g' docker-compose.yaml

      # CodeDeploy 배포를 위한 관련 파일 업로드용 디렉토리 생성
      - name: Create zip file for AWS CodeDeploy
        run: mkdir ${{ env.AWS_CODE_DEPLOY_NAME }} && cp -r appspec.yml image.txt docker-compose.yaml scripts ${{ env.AWS_CODE_DEPLOY_NAME }}

      # AWS S3로 배포 관련 파일 압축 및 업로드
      - name: Upload to AWS S3
        run: |
          aws deploy push \
            --application-name ${{ env.AWS_CODE_DEPLOY_NAME }} \
            --s3-location s3://${{ env.AWS_S3_BUCKET_NAME }}/codedeploy/$GITHUB_SHA.zip \
            --ignore-hidden-files \
            --source ${{ env.AWS_CODE_DEPLOY_NAME }}

      # AWS EC2 CodeDeploy 배포 요청
      - name: Deploy to AWS EC2
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.AWS_CODE_DEPLOY_NAME }} \
            --s3-location bucket=$AWS_S3_BUCKET_NAME,key=codedeploy/$GITHUB_SHA.zip,bundleType=zip \
            --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }} \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --description "Deploy cicd-study"

