name: Java CI with Gradle

on:
  push:
    branches: [ "study" ]

env:
  ECR_URL: 491092715218.dkr.ecr.ap-northeast-2.amazonaws.com/cicd-study
  ROLE_ARN: arn:aws:iam::491092715218:role/cicd-study-oicd-role
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET_NAME: bom-cicdstudy-bucket # S3 버킷 이름 # ${{ secrets.AWS_S3_BUCKET_NAME }}
  AWS_CODE_DEPLOY_NAME: bom-cicd-study # CodeDeploy 애플리케이션 이름
  AWS_CODE_DEPLOY_GROUP: cicd-study-codedeploy-group # CodeDeploy 배포 그룹 이름


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v3

      - name: set JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Run chmod to make gradlew executable
        run: chmod +x gradlew

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Docker build
        run: docker build -t ${{ env.ECR_URL }}:latest ./

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions
          role-to-assume: ${{ env.ROLE_ARN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Publish Image to ECR
        run: |
          docker push ${{ env.ECR_URL }}:latest

      # Docker 이미지 이름을 image.txt 파일에 쓰기
      - name: Write Docker image name to file
        run: echo "${{ env.ECR_URL }}:latest" > image.txt

      # CodeDeploy 배포를 위한 관련 파일 업로드용 디렉토리 생성
      - name: Create zip file for AWS CodeDeploy
        run: mkdir ${{ env.AWS_CODE_DEPLOY_NAME }} && cp -r appspec.yml image.txt scripts ${{ env.AWS_CODE_DEPLOY_NAME }}

      # AWS 설정
      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      # AWS S3로 배포 관련 파일 압축 및 업로드
      - name: Upload to AWS S3
        run: |
          aws deploy push \
            --application-name ${{ env.AWS_CODE_DEPLOY_NAME }} \
            --s3-location s3://${{ env.AWS_S3_BUCKET_NAME }}/codedeploy/$GITHUB_SHA.zip \
            --ignore-hidden-files \
            --source ${{ env.AWS_CODE_DEPLOY_NAME }}

      # AWS EC2 CodeDeploy 배포 요청
      - name: Delpoy to AWS EC2
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.AWS_CODE_DEPLOY_NAME }} \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }} \
            --description "Deploy cicd-study" \
            --s3-location bucket=$AWS_S3_BUCKET_NAME,key=codedeploy/$GITHUB_SHA.zip,bundleType=zip

